#.travis.yml

language: node_js
node_js:
  - "9.0"

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod
  
notifications:
  slack: git-gud-workspace:ENPyEfwTZtAjfFDdgmJeTWe1
