language: node_js
node_js:
- '9.0'
before_script:
- npm install -g @angular/cli
- npm install
script:
- ng build --prod
before_install:
- openssl aes-256-cbc -K $encrypted_36a051a84034_key -iv $encrypted_36a051a84034_iv
  -in pts6-bijbaan-secret.json.enc -out pts6-bijbaan-secret.json -d
#deploy:
#  provider: gae
#  keyfile: client-secret.json
#  project: pts6-bijbaan
#  on:
#    all_branches: true
