#.travis.yml

language: node_js
node_js:
  - "9.0"

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng lint
  - ng build --prod --base-href="https://vaifreecams.com/"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f532364904ea_key -iv $encrypted_f532364904ea_iv
    -in pts-bijbaan-service-account.json.enc -out pts-bijbaan-service-account.json
    -d

deploy:
  provider: gae
  keyfile: pts-bijbaan-service-account.json
  project: pts6-bijbaan
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack: git-gud-workspace:ENPyEfwTZtAjfFDdgmJeTWe1
