# [START runtime]
runtime: nodejs10
handlers:
  - url: /
    static_files: dist/frontend-bijbaan/index.html
    upload: dist/frontend-bijbaan/index.html
  - url: /
    static_dir: dist/frontend-bijbaan
# [END runtime]
